secret_key_base: 0fPZ5K5beHX-z4c5hE5z0Uu4FKHguxCa1MinDexjdh4
port: 3000
name: wedding-be

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
    
host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:password@localhost:5432/wedding_be_test
auto_reload: false

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
